version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "123"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: ["redis-server", "--requirepass", "123"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "123"
      RATE_LIMITER_IP_LIMIT: "10"
      RATE_LIMITER_TOKEN_LIMIT: "100"
      RATE_LIMITER_BLOCK_DURATION: "300"
    depends_on:
      redis:
        condition: service_healthy
